name: Test build/test linux gpu

on:
  pull_request:

jobs:
  build-test:
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      runner: linux.4xlarge.nvidia.gpu
      gpu-arch-type: cuda
      gpu-arch-version: "12.1"
      timeout: 240
      script: |
        pushd ..
        # install triton
        git clone git@github.com:triton-lang/triton.git
        pushd triton
        pip install ninja cmake wheel; # build-time dependencies
        pip install -e python
        git clone git@github.com:pytorch/pytorch.git
        pushd pytorch
        git submodule sync
        git submodule update --init --recursive
        pip install -r requirements.txt
        pip install mkl-static mkl-include
        # CUDA only: Add LAPACK support for the GPU if needed
        conda install -c pytorch magma-cuda121
        python setup.py install
        pytest test/inductor


  build-test-cpu:
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
    timeout: 240
      script: |
        pushd ..
        echo "Installing triton..." "hello"
        # install triton
        git clone git@github.com:pytorch/pytorch.git
        echo "Checking directory..." "hello"
        ls
        pushd pytorch
        echo "Checking submodule..." "hello"
        ls
        git submodule sync
        echo "Updating submodule..." "hello"
        ls
        git submodule update --init --recursive
        echo "Installing requirements..." "hello"
        ls
        pip install -r requirements.txt
        python setup.py install
        # pytest test/inductor