name: Test build/test linux gpu

on:
  pull_request:
  workflow_dispatch:
    inputs:
      triton_pin:
        description: 'Triton branch or commit to pin'
        default: 'main'
        required: false
      pytorch_pin:
        description: 'PyTorch branch or commit to pin'
        default: 'main'
        required: false

jobs:
  build-test:
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      runner: linux.4xlarge.nvidia.gpu
      gpu-arch-type: cuda
      gpu-arch-version: "12.1"
      timeout: 240
      script: |
        set -x
        pushd ..
        # install triton
        git clone https://github.com/triton-lang/triton.git
        pushd triton
        git checkout ${{ github.event.inputs.triton_pin || 'main' }}
        pip install ninja cmake wheel # build-time dependencies
        sleep 1000
        pip install -e python
        git clone https://github.com/pytorch/pytorch.git
        pushd pytorch
        git checkout ${{ github.event.inputs.pytorch_pin || 'main' }}
        git submodule sync
        git submodule update --init --recursive
        pip install -r requirements.txt
        pip install mkl-static mkl-include pytest
        # CUDA only: Add LAPACK support for the GPU if needed
        conda install -c pytorch magma-cuda121
        python setup.py install
        pytest test/inductor

  build-test-cpu:
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      timeout: 240
      script: |
        set -x
        pushd ..
        echo "Installing triton..." "hello"
        # install triton
        git clone https://github.com/triton-lang/triton.git
        pushd triton
        git checkout ${{ github.event.inputs.triton_pin || 'main' }}
        pip install ninja cmake wheel
        sleep 1000
        pip install -e python
        git clone https://github.com/pytorch/pytorch.git
        pushd pytorch
        git checkout ${{ github.event.inputs.pytorch_pin || 'main' }}
        git submodule sync
        git submodule update --init --recursive
        pip install -r requirements.txt
        pip install pytest
        python setup.py install
        pytest test/inductor
