name: vLLM Benchmark

on:
  schedule:
    # Run every 6 hours (4 times a day)
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Allow manual triggering
  pull_request:
    paths:
      - .github/workflows/vllm-benchmark.yml

jobs:
  benchmark-h100:
    name: Run vLLM benchmarks
    runs-on: linux.aws.h100.4
    environment: ${{ github.ref == 'refs/heads/main' && 'pytorch-x-vllm' || 'pytorch-x-vllm' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout vLLM repository
        uses: actions/checkout@v4
        with:
          repository: vllm-project/vllm
          path: vllm-benchmarks/vllm
          ref: main

      - name: Setup benchmark tests
        working-directory: vllm-benchmarks
        run: |
          # Set the list of benchmarks we want to cover in PyTorch infra
          cp -r benchmarks/*.json vllm/.buildkite/nightly-benchmarks/tests

      - name: Set GPU device name
        working-directory: vllm-benchmarks
        run: |
          export GPU_DEVICE=$(nvidia-smi -i 0 --query-gpu=name --format=csv,noheader | awk '{print $2}')
          echo "GPU_DEVICE=$GPU_DEVICE" >> $GITHUB_ENV

      - name: Check for last benchmark commit
        working-directory: vllm-benchmarks
        run: |
          HEAD_BRANCH=main

          pushd vllm
          HEAD_SHA=$(git rev-parse --verify HEAD)
          popd

          echo "HEAD_SHA=$HEAD_SHA" >> $GITHUB_ENV

      - name: Setup GPU_FLAG for docker run
        run: |
          echo "GPU_FLAG=--gpus all -e NVIDIA_DRIVER_CAPABILITIES=all" >> "${GITHUB_ENV}"

      - name: Setup SCCACHE_SERVER_PORT environment for docker run when on container
        run: |
          echo "SCCACHE_SERVER_PORT_DOCKER_FLAG=-e SCCACHE_SERVER_PORT=$((RUNNER_UID + 4226))" >> "${GITHUB_ENV}"

      - name: Run vLLM benchmark
        env:
          SCCACHE_BUCKET: ossci-compiler-cache-circleci-v2
          SCCACHE_REGION: us-east-1
          HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
          DOCKER_IMAGE: public.ecr.aws/q9t5s3a7/vllm-ci-postmerge-repo:${{ env.HEAD_SHA }}
        run:
          set -x

          docker run --gpus all -e NVIDIA_DRIVER_CAPABILITIES=all "${DOCKER_IMAGE}" bash -xc "ls -la"


#            ${SCCACHE_SERVER_PORT_DOCKER_FLAG:-} \
#            -e SCCACHE_BUCKET \
#            -e SCCACHE_REGION \
#            -e GPU_DEVICE \
#            -e HUGGING_FACE_HUB_TOKEN \
#            --security-opt seccomp=unconfined \
#            --cap-add=SYS_PTRACE \
#            --ipc=host \
#            --tty \
#            --detach \
#            -v "${GITHUB_WORKSPACE}:/tmp/workspace" \
#            -w /tmp/workspace \
#            "${DOCKER_IMAGE}" \
#            "ls -la"
